language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: COMPOSER_FLAGS="--dev"
        - php: nightly
          env: COMPOSER_FLAGS="--dev"
    allow_failures:
        - php: nightly

services:
    - mongodb

before_install:
    - INI_FILE=$(echo "<?php echo get_cfg_var('cfg_file_path');"|php);
    - echo $INI_FILE;
    - echo extension=mongodb.so >> $INI_FILE;

install:
    - composer update $COMPOSER_FLAGS --no-interaction -v
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.0.0/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - phpunit --verbose
    - phpenv config-rm xdebug.ini || return 0
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run --diff -vvv fix; fi
